# Generated by Django 5.1.4 on 2025-01-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_group_group_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
